# pybricks blocks file:{"blocks":{"languageVersion":0,"blocks":[{"type":"blockGlobalSetup","id":"bjK,wS1MYO7aiYkFSwd{","x":139,"y":61,"deletable":false,"next":{"block":{"type":"variables_setup_imported_function","id":"gl-AK.r40_xSC_3Goq$w","fields":{"FROM_MODULE":{"id":"py9Z9}e=M*y[TV,S8R`}"},"VAR":{"id":"3p4[I[d2gmvDqtMCvu`h"}},"next":{"block":{"type":"variables_setup_imported_function","id":"7kz:il/P|(]K}aM?bYeL","fields":{"FROM_MODULE":{"id":"py9Z9}e=M*y[TV,S8R`}"},"VAR":{"id":"p31Sh0]%`C|qd;ojomQ-"}}}}}}},{"type":"blockGlobalStart","id":"3tJe|AWl0baN(wH9a$@.","x":-163,"y":62,"deletable":false},{"type":"variables_setup_function","id":"hjSvf~3kt_W,Dv_+tB5{","x":137,"y":291,"extraState":{"optionLevel":0},"fields":{"ICON":"TASK","VAR":{"id":"v+K2U#=*ezBhNS2=2vvc"}},"inputs":{"STACK":{"block":{"type":"blockImportTaskCallStatement","id":"}^=#u;_(ku%3:%e.T%ej","extraState":{"optionLevel":1},"inputs":{"VAR":{"shadow":{"type":"variables_get_imported_function","id":"{4C|lG^,_7d[;8o}~S^{","fields":{"VAR":{"id":"p31Sh0]%`C|qd;ojomQ-","name":"virarAngulo","type":"FunctionImported"}}}},"ARG0":{"shadow":{"type":"blockMathNumber","id":"L#!IRIiPk8!SJU1T}_}i","fields":{"NUM":-80}}}},"next":{"block":{"type":"blockImportTaskCallStatement","id":"v=%;2Wc0lw_u)}B{S5h3","extraState":{"optionLevel":2},"inputs":{"VAR":{"shadow":{"type":"variables_get_imported_function","id":"];5d81r2x8^6C.o0:OI^","fields":{"VAR":{"id":"3p4[I[d2gmvDqtMCvu`h","name":"andarReto","type":"FunctionImported"}}}},"ARG0":{"shadow":{"type":"blockMathNumber","id":"R$~)4(Wj+UrWiY@#N~u-","fields":{"NUM":1255}}},"ARG1":{"shadow":{"type":"blockMathNumber","id":";T^8$Iw^e*@Rx9bmMSd|","fields":{"NUM":0}},"block":{"type":"blockTextLiteral","id":"ZzqUQ%]w^Du,]L/p9gho","fields":{"TEXT":"continue"}}}}}}}}}}]},"variables":[{"name":"red","id":"Z0)5TK%@bXKCeTY?l-bW","type":"ColorDef"},{"name":"orange","id":"iyr/dO_^xu{.+yN59.jC","type":"ColorDef"},{"name":"yellow","id":"Fmeb=^b2p9/={Y]!WruA","type":"ColorDef"},{"name":"green","id":"MD}mYzI0Y9k9p@[ha9v;","type":"ColorDef"},{"name":"cyan","id":"83?nOw(,K@YzaKWj9u:A","type":"ColorDef"},{"name":"blue","id":"h:f#~rwr^)5E[ga?yH}[","type":"ColorDef"},{"name":"violet","id":"9vBOcJzT@lkcM`BrkeFB","type":"ColorDef"},{"name":"magenta","id":"pkbF~w1t|Eypu34MQbX[","type":"ColorDef"},{"name":"white","id":"_*iA;bamdes;B[!@Ck;w","type":"ColorDef"},{"name":"none","id":"Sf`X|ovf%+B!gw{$DM4:","type":"ColorDef"},{"name":"Chassi","id":"py9Z9}e=M*y[TV,S8R`}","type":"ModuleImported"},{"name":"andarReto","id":"3p4[I[d2gmvDqtMCvu`h","type":"FunctionImported"},{"name":"virarAngulo","id":"p31Sh0]%`C|qd;ojomQ-","type":"FunctionImported"},{"name":"Principal","id":"v+K2U#=*ezBhNS2=2vvc","type":"Function"}],"info":{"type":"pybricks","version":"1.3.2"}}
from Chassi import andarReto, virarAngulo

def Principal():
    virarAngulo(-80)
    andarReto(1255, 'continue')


# The main program starts here.
