# pybricks blocks file:{"blocks":{"languageVersion":0,"blocks":[{"type":"blockGlobalSetup","id":"bjK,wS1MYO7aiYkFSwd{","x":-16,"y":78,"deletable":false,"next":{"block":{"type":"variables_set_prime_hub","id":"CD1jWk2hp0#?S$bX4:xI","extraState":{"optionLevel":0},"fields":{"VAR":{"id":"jt{6]eY?q++vkfWh5HTy"}},"next":{"block":{"type":"variables_set_motor","id":"STsgW(c(GuMBsQYGPcWx","fields":{"VAR":{"id":"[[pESarwa?y8F/|@C-4W"}},"inputs":{"PORT":{"shadow":{"type":"blockParametersPort","id":"^#H|E0kp--:!40t+siGn","fields":{"NAME":"A"}}},"POSITIVE_DIRECTION":{"shadow":{"type":"blockParametersDirection","id":"%tGC|d!BV@k?b;^HZ_{5","fields":{"SELECTION":"Direction.CLOCKWISE"}}}},"next":{"block":{"type":"variables_set_motor","id":"d;A?~#2/L.Fn%VHVJHeu","fields":{"VAR":{"id":"fn*;pQ=h?$-ozqGa7S2N"}},"inputs":{"PORT":{"shadow":{"type":"blockParametersPort","id":"]FDH?XyuWo5s{ZG:@n[q","fields":{"NAME":"B"}}},"POSITIVE_DIRECTION":{"shadow":{"type":"blockParametersDirection","id":"+9R-;0I(^+z*j{R9xhe`","fields":{"SELECTION":"Direction.CLOCKWISE"}}}}}}}}}}},{"type":"blockGlobalStart","id":"3tJe|AWl0baN(wH9a$@.","x":513,"y":62,"deletable":false,"next":{"block":{"type":"blockMotorRun","id":"zuNdCB?*bA`qKpc,!@aY","extraState":{"optionLevel":1},"fields":{"METHOD":"MOTOR_RUN_FOR"},"inputs":{"VAR":{"shadow":{"type":"variables_get_motor_device","id":"]ZsNFfIMIY^V0l=A*-w@","fields":{"VAR":{"id":"[[pESarwa?y8F/|@C-4W","name":"motor","type":"Motor"}}}},"VALUE0":{"shadow":{"type":"unit_angularVelocity","id":"wUz+B0v{pXUyK9[SPI3+","fields":{"VALUE0":500}}},"ANGLE":{"shadow":{"type":"unit_angle","id":"#eOTMEit4:3,@P+)rS[N","fields":{"VALUE0":360}}},"THEN":{"shadow":{"type":"parameters_stop_4","id":"x_M+9,C-.9lqp~6;7|nB","fields":{"VALUE":"Stop.HOLD"}}}}}}},{"type":"blockPrint","id":"j,,T}?rBkaW$1v?olp4p","x":514,"y":254,"enabled":false,"extraState":{"optionLevel":0},"inputs":{"TEXT0":{"shadow":{"type":"text","id":"!x5.0YiWya^`(y)yO5B8","fields":{"TEXT":"Hello, Pybricks!"}}}}}]},"variables":[{"name":"red","id":"XfxGOI97E:jDh=zk]|Hh","type":"ColorDef"},{"name":"orange","id":"R)tYR`{g%5MTbN]]F255","type":"ColorDef"},{"name":"yellow","id":"TwIcAI9.jurWX*Qj%UCc","type":"ColorDef"},{"name":"green","id":"33^CV]NB5w7#!p7`}s-I","type":"ColorDef"},{"name":"cyan","id":"c_%Asb+JliQYr}z)Lg~J","type":"ColorDef"},{"name":"blue","id":"O23pHMS9v3p$R)Qe`7|#","type":"ColorDef"},{"name":"violet","id":"j|*.D+Rt;8r3cF?e*4Qy","type":"ColorDef"},{"name":"magenta","id":"z?[!`qmA._7h24AfZ2,}","type":"ColorDef"},{"name":"white","id":"W~{?wTFQD0e(XMRR`QC5","type":"ColorDef"},{"name":"none","id":"BL*n00$D/S}8P,{uf:56","type":"ColorDef"},{"name":"prime hub","id":"jt{6]eY?q++vkfWh5HTy","type":"PrimeHub"},{"name":"motor","id":"[[pESarwa?y8F/|@C-4W","type":"Motor"},{"name":"motor 2","id":"fn*;pQ=h?$-ozqGa7S2N","type":"Motor"}],"info":{"type":"pybricks","version":"1.3.2"}}
from pybricks.hubs import PrimeHub
from pybricks.parameters import Direction, Port, Stop
from pybricks.pupdevices import Motor

# Set up all devices.
prime_hub = PrimeHub()
motor = Motor(Port.A, Direction.CLOCKWISE)
motor_2 = Motor(Port.B, Direction.CLOCKWISE)


# The main program starts here.
motor.run_angle(500, 360)
